Repository charmbracelet/vhs, pull requests merged in 2022-10, with the labels that each got.

#53 docs: improve Docker instructions
  Dockerfile
  README.md
Labels: enhancement

#58 docs: fix arch install instructions
  README.md
Labels: documentation

#54 feat: authorized keys
  README.md
  serve.go
Labels: enhancement

#89 fix: leakless windows fix
  evaluator.go
  vhs.go
Labels: bug

#101 chore: add dependabot config
  .github/dependabot.yml
Labels: enhancement

#100 fix: don't print errors twice
  main.go
Labels: bug

#99 chore: use a context to control the recording process
  evaluator.go
  vhs.go
Labels: bug

#112 fix: use cmd as default on windows
  tty.go
Labels: bug

#83 feat: support named themes
  .gitattributes
  Makefile
  README.md
  THEMES.md
  command.go
  command_test.go
  examples/fixtures/all.tape
  examples/settings/set-theme-name.tape
  examples/settings/theme-name.gif
  examples/settings/theme.gif
  lexer_test.go
  main.go
  man.go
  parser_test.go
  scripts/download_theme.sh
  theme.go
  themes.go
  themes.json
  themes_custom.json
  themes_test.go
Labels: enhancement
